#!/bin/bash

# 检查参数数量是否正确
if [ $# -ne 2 ]; then
    echo "用法: $0 <输入文件路径> <输出文件路径>"
    exit 1
fi

input_file="$1"
output_file="$2"

# 检查输入文件是否存在
if [ ! -f "$input_file" ]; then
    echo "错误: 输入文件 $input_file 不存在。"
    exit 1
fi

cat $input_file | while read line
do
    # 跳过空行
    if [ -z "$line" ]; then
        continue
    fi
    echo $line
    curl -w "%{http_code} $line\n" -o /dev/null -s -m 3 "$line" | grep "^200 " | cut -d " " -f 2- >> "$output_file"
done
echo "处理完成，有效地址已追加到 $output_file。"
